In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('AIML.csv')

In [3]:
dataset

Gender  CLIENTNUM  Customer_Age  Months_on_book  Total_Relationship_Count
0       M  768805383            45              39                         5
1       F  818770008            49              44                         6
2       M  713982108            51              36                         4
3       F  769911858            40              34                         3
4       M  709106358            40              21                         5
..    ...        ...           ...             ...                       ...
94      F  715550508            45              28                         5
95      M  719712633            64              52                         6
96      M  772629333            45              35                         5
97      M  720336708            53              35                         5
98      M  802013583            56              50                         3

[99 rows x 5 columns]

In [4]:
dataset.isnull().sum()

Gender                      0
CLIENTNUM                   0
Customer_Age                0
Months_on_book              0
Total_Relationship_Count    0
dtype: int64

In [16]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

In [18]:
x

array([['M', 768805383, 45, 14],
       ['F', 818770008, 49, 19],
       ['M', 713982108, 51, 11],
       ['F', 769911858, 40, 9],
       ['M', 709106358, 40, 1],
       ['M', 713061558, 44, 11],
       ['M', 810347208, 51, 21],
       ['M', 818906208, 32, 2],
       ['M', 710930508, 37, 11],
       ['M', 719661558, 48, 11],
       ['M', 708790833, 42, 6],
       ['M', 710821833, 65, 27],
       ['M', 710599683, 56, 11],
       ['M', 816082233, 35, 5],
       ['F', 712396908, 57, 23],
       ['M', 714885258, 44, 12],
       ['M', 709967358, 48, 11],
       ['M', 753327333, 41, 9],
       ['M', 806160108, 61, 28],
       ['F', 709327383, 45, 12],
       ['M', 806165208, 47, 17],
       ['F', 708508758, 62, 24],
       ['M', 784725333, 41, 8],
       ['F', 811604133, 47, 11],
       ['M', 789124683, 54, 17],
       ['F', 771071958, 41, 3],
       ['M', 720466383, 59, 21],
       ['M', 804424383, 63, 28],
       ['F', 718813833, 44, 9],
       ['M', 806624208, 47, 17],
       ['M', 778348

In [19]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
from sklearn.compose import ColumnTransformer
le_x = LabelEncoder()
x[:,0] = le_x.fit_transform(x[:,0])
ohe_x = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(),[0])], 
    remainder = 'passthrough'
)
x = np.array(ohe_x.fit_transform(x), dtype = np.int)

In [20]:
x

array([[        0,         1, 768805383,        45,        14],
       [        1,         0, 818770008,        49,        19],
       [        0,         1, 713982108,        51,        11],
       [        1,         0, 769911858,        40,         9],
       [        0,         1, 709106358,        40,         1],
       [        0,         1, 713061558,        44,        11],
       [        0,         1, 810347208,        51,        21],
       [        0,         1, 818906208,        32,         2],
       [        0,         1, 710930508,        37,        11],
       [        0,         1, 719661558,        48,        11],
       [        0,         1, 708790833,        42,         6],
       [        0,         1, 710821833,        65,        27],
       [        0,         1, 710599683,        56,        11],
       [        0,         1, 816082233,        35,         5],
       [        1,         0, 712396908,        57,        23],
       [        0,         1, 714885258,

In [21]:
x=x[:,1:]

In [22]:
x

array([[        1, 768805383,        45,        14],
       [        0, 818770008,        49,        19],
       [        1, 713982108,        51,        11],
       [        0, 769911858,        40,         9],
       [        1, 709106358,        40,         1],
       [        1, 713061558,        44,        11],
       [        1, 810347208,        51,        21],
       [        1, 818906208,        32,         2],
       [        1, 710930508,        37,        11],
       [        1, 719661558,        48,        11],
       [        1, 708790833,        42,         6],
       [        1, 710821833,        65,        27],
       [        1, 710599683,        56,        11],
       [        1, 816082233,        35,         5],
       [        0, 712396908,        57,        23],
       [        1, 714885258,        44,        12],
       [        1, 709967358,        48,        11],
       [        1, 753327333,        41,         9],
       [        1, 806160108,        61,      

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.30,random_state = 0)

In [25]:
from sklearn.linear_model import LinearRegression 
regress = LinearRegression()
regress.fit(x_train, y_train)

LinearRegression()

In [26]:
y_pred = regress.predict(x_test)

In [27]:
y_pred

array([4.2612997 , 4.49244297, 4.41000007, 4.00477676, 4.45467329,
       4.27153601, 4.33509006, 4.31621905, 4.5260787 , 4.18315622,
       4.36215968, 4.29539404, 4.65995156, 4.38801433, 4.42540149,
       4.64861474, 4.38021597, 4.37840337, 4.12722644, 4.08225914,
       4.41935851, 4.23201407, 3.93777016, 3.94093732, 4.5674971 ,
       4.27682629, 4.20160241, 4.16849822, 3.82551568, 4.00997498])

In [28]:
y_test

array([4, 4, 4, 6, 5, 4, 6, 6, 1, 5, 4, 4, 6, 5, 2, 3, 4, 4, 5, 5, 5, 5,
       3, 5, 3, 4, 6, 3, 2, 6])

In [29]:
regress.score(x_train, y_train)

0.021686755052878537

In [30]:
regress.score(x_test, y_test)

-0.06905186864079838

In [31]:
import statsmodels.api as sm

In [33]:
x = np.append(arr = np.ones(shape = (99,4), dtype = int), values = x, axis =1)

In [35]:
x

array([[        1,         1,         1,         1,         1, 768805383,
               45,        14],
       [        1,         1,         1,         1,         0, 818770008,
               49,        19],
       [        1,         1,         1,         1,         1, 713982108,
               51,        11],
       [        1,         1,         1,         1,         0, 769911858,
               40,         9],
       [        1,         1,         1,         1,         1, 709106358,
               40,         1],
       [        1,         1,         1,         1,         1, 713061558,
               44,        11],
       [        1,         1,         1,         1,         1, 810347208,
               51,        21],
       [        1,         1,         1,         1,         1, 818906208,
               32,         2],
       [        1,         1,         1,         1,         1, 710930508,
               37,        11],
       [        1,         1,         1,         1,    

In [36]:
x_ov = x[:,[0,1,2,3,4,5]] 
regress_ols = sm.OLS(endog=y, exog = x_ov).fit() 
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                 -0.015
Method:                 Least Squares   F-statistic:                    0.2917
Date:                Tue, 26 Jan 2021   Prob (F-statistic):              0.748
Time:                        17:24:14   Log-Likelihood:                -171.00
No. Observations:                  99   AIC:                             348.0
Df Residuals:                      96   BIC:                             355.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6832      0.660      1.035      0.303      -0.627       1.994
x1             0.6832      0.660      1.035      0.303      -0.627       1.994
x2             0.6832      0.660      1.035      0.303      -0.627       1.994
x3             0.6832      0.660      1.035      0.303      -0.627       1.994
x4             0.1501      0.302      0.498      0.620      -0.448       0.749
x5          1.843e-09   3.55e-09      0.519      0.605   -5.21e-09    8.89e-09
==============================================================================
Omnibus:                       13.380   Durbin-Watson:                   2.358
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                5.306
Skew:                          -0.299   Prob(JB):                       0.0705
Kurtosis:                       2.037   Cond. No.                     2.92e+26
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.5e-34. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [37]:
x_ov

array([[        1,         1,         1,         1,         1, 768805383],
       [        1,         1,         1,         1,         0, 818770008],
       [        1,         1,         1,         1,         1, 713982108],
       [        1,         1,         1,         1,         0, 769911858],
       [        1,         1,         1,         1,         1, 709106358],
       [        1,         1,         1,         1,         1, 713061558],
       [        1,         1,         1,         1,         1, 810347208],
       [        1,         1,         1,         1,         1, 818906208],
       [        1,         1,         1,         1,         1, 710930508],
       [        1,         1,         1,         1,         1, 719661558],
       [        1,         1,         1,         1,         1, 708790833],
       [        1,         1,         1,         1,         1, 710821833],
       [        1,         1,         1,         1,         1, 710599683],
       [        1,       

In [38]:
x_ovc = x_ov[:,1:]

In [40]:
from sklearn.model_selection import train_test_split
x_ov_train, x_ov_test, y_ov_train, y_ov_test = train_test_split(x_ov,y,test_size=.30,random_state=0)

from sklearn.linear_model import LinearRegression 
regress_ov1 = LinearRegression() 
regress_ov1.fit(x_ov_train, y_ov_train)

LinearRegression()

In [41]:
regress_ov1.score(x_ov_train, y_ov_train)

0.012897291512731224

In [42]:
regress_ov1.score(x_ov_test, y_ov_test)

-0.037430094327804087

In [43]:
x_ov = x[:,[0,1,2,3,5]] 
regress_ols = sm.OLS(endog=y, exog = x_ov).fit() 
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                 -0.007
Method:                 Least Squares   F-statistic:                    0.3381
Date:                Tue, 26 Jan 2021   Prob (F-statistic):              0.562
Time:                        17:29:32   Log-Likelihood:                -171.13
No. Observations:                  99   AIC:                             346.3
Df Residuals:                      97   BIC:                             351.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6715      0.657      1.022      0.309      -0.633       1.976
x1             0.6715      0.657      1.022      0.309      -0.633       1.976
x2             0.6715      0.657      1.022      0.309      -0.633       1.976
x3             0.6715      0.657      1.022      0.309      -0.633       1.976
x4          2.044e-09   3.52e-09      0.582      0.562   -4.93e-09    9.02e-09
==============================================================================
Omnibus:                       14.073   Durbin-Watson:                   2.347
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                5.646
Skew:                          -0.326   Prob(JB):                       0.0594
Kurtosis:                       2.029   Cond. No.                     2.39e+35
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.73e-52. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [44]:
x_ovc = x_ov[:,1:]
x_ov_train, x_ov_test, y_ov_train, y_ov_test = train_test_split(x_ov,y,test_size=.30,random_state=0)

from sklearn.linear_model import LinearRegression 
regress_ov2 = LinearRegression() 
regress_ov2.fit(x_ov_train, y_ov_train)

LinearRegression()

In [45]:
 regress_ov2.score(x_ov_train, y_ov_train)

0.0006050480113982681

In [46]:
 regress_ov2.score(x_ov_test, y_ov_test)

-0.00196607368398527

In [47]:
x_ov = x[:,[0,1,2,3]] 
regress_ols = sm.OLS(endog=y, exog = x_ov).fit() 
regress_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Tue, 26 Jan 2021   Prob (F-statistic):                nan
Time:                        17:31:02   Log-Likelihood:                -171.30
No. Observations:                  99   AIC:                             344.6
Df Residuals:                      98   BIC:                             347.2
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0530      0.034     30.541      0.000       0.985       1.121
x1             1.0530      0.034     30.541      0.000       0.985       1.121
x2             1.0530      0.034     30.541      0.000       0.985       1.121
x3             1.0530      0.034     30.541      0.000       0.985       1.121
==============================================================================
Omnibus:                       13.895   Durbin-Watson:                   2.352
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                5.519
Skew:                          -0.315   Prob(JB):                       0.0633
Kurtosis:                       2.030   Cond. No.                     2.10e+48
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.99e-95. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [49]:
x_ovc = x_ov[:,1:]
x_ov_train, x_ov_test, y_ov_train, y_ov_test = train_test_split(x_ov,y,test_size=.30,random_state=0)

from sklearn.linear_model import LinearRegression 
regress_ov3 = LinearRegression() 
regress_ov3.fit(x_ov_train, y_ov_train)

LinearRegression()

In [50]:
 regress_ov3.score(x_ov_train, y_ov_train)

0.0

In [51]:
 regress_ov3.score(x_ov_test, y_ov_test)

-0.0094818611957741

In [52]:
x_ov

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1,